function [fitresult,xData, gof] = createFit(logx, bprime)
%CREATEFIT(LOGX,BPRIME)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : logx
%      Y Output: bprime
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Sep-2014 08:47:05


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( logx, bprime );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( ft );
opts.SmoothingParam = 0.99;
ex = excludedata( xData, yData, 'Indices', [36 37] );
opts.Exclude = ex;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
%figure( 'Name', 'untitled fit 1' );
%h = plot( fitresult, xData, yData, ex );
%legend( h, 'bprime vs. logx', 'Excluded bprime vs. logx', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
%xlabel( 'logx' );
%ylabel( 'bprime' );
%grid on


